### ISSUE TITLE
j-help redefines if-let

### ISSUE THREAD

**Issue by ag91** [zellio/j-mode#18]
Hi there,

thanks to provide a nice emacs mode to work with J (which as far as I have tries is a really cool language!).

I have noticed that j-help mode redefines the if-let macro globally: is this right? That name is already used by subr-x.el and it is used by other packages.

**Comment by LdBeth** [comment]
`j-help.el` has be refactored to use a new helper function `j-help--process-voc-list` and old helper functions are removed.
