### ISSUE TITLE
After j-mode has been activated, wrong type errors

### ISSUE THREAD

**Issue by theSherwood** [zellio/j-mode#21]
After j-mode gets activated, I often end up with type errors on unconnected commands.

Eg:

```
Error running timer 'which-key--update': (wrong-type-argument: listp popup)
```

I'm pretty certain the error is resulting from this package because when I uninstall this package and reload, the errors no longer appear. And I've had this same issue while running emacs and j-mode on macOS and on android in termux.

**Comment by LdBeth** [comment]
I have been using the updated j-mode with which-key long enough that I think this problem has been resolved.
