### ISSUE TITLE
Improper syntax colouring for copula when variables are within a string

### ISSUE THREAD

**Issue by jthulhu** [zellio/j-mode#22]
if I write `a =. 3`, `=.` is colored as a copula. If I write `'a b' =. 1;2`, `=` is colored as a verb, and `.` as a conjunction or as an adverb (as I use the same colouring for both conjunctions and adverbs).
However, this is only a colouring problem, since if I call `j-help-lookup-symbol-at-point` on either `=` or `.`, they both point to `=.`.

**Comment by LdBeth** [comment]
This has been fixed by new font lock rules implemented.
