### ISSUE TITLE
Improper handling of parenthesis in a `define` block

### ISSUE THREAD

**Issue by jthulhu** [zellio/j-mode#23]
Since in J most of the times, braces, brackets are not meant to be paired with an other opening/closing one. These are handled fine, since Emacs doesn't warn you of a no matching brace or bracket. However, in the following snippet
```j
b =. verb define
a =. 3
)
```
when typing the last parenthesis, Emacs warns about a non-matching parenthesis, which it should not do.

**Comment by Eason0210** [comment]
I recommend you disable `electric-pair-mode` in J

You can set something like:
```emacs-lisp
(add-hook 'inferior-j-mode-hook (lambda () (electric-pair-mode -1)))
```

**Comment by LdBeth** [comment]
The new font lock implementation now takes care of imbalanced parentheses by using custom `syntax-propertize-function`.
